require("plugin_config.lualine")
require("plugin_config.nvim-tree")
require("plugin_config.catppuchin")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.gitsigns")
require("plugin_config.deadcolumn")
