# Get editor completions based on the config schema
##"$schema" = 'https://starship.rs/config-schema.json'

#format = '''
#(bold green)$directory$rust$package
#[└─➜](bold green) '''

# Move the directory to the second line
##format = '$directory$character'

# Inserts a blank line between shell prompts
##add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
##[character] # The name of the module we are configuring is 'character'
##success_symbol = '[➜](bold green)'
##error_symbol = '[➜](red)'
##vimcmd_symbol = "[❮](green)"
# The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
##[package]
##disabled = true

format = """
[░▒▓](#a3aed2)\
[ 3L ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
[](fg:#212736)$character"""

add_newline = false

[character] 
success_symbol = '[➜](bold green)'
error_symbol = '[➜](red)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)" 
truncation_length = 8
#truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
