import = ["/home/victor/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 8

[font.normal]
family = "JetBrainsMonoNLNerdFontMono"

[window.padding]
x = 5
y = 3

[keyboard]
bindings = [{ key = "Return", mods = "Super|Shift", action = "SpawnNewInstance"},]
